name: chat_server
description: A simple chat server for the Flutter app.

environment:
  sdk: ">=2.18.0 <3.0.0" # Match your Dart SDK version

dependencies:
  shelf: ^1.4.2
  shelf_router: ^1.0.0 # Use ^1.0.0 if ^1.0.1 causes issues
  shelf_static: ^1.1.0
  json_annotation: ^4.8.0

dev_dependencies:
  build_runner: ^2.4.6
  json_serializable: ^6.6.2
